WIP: Shooter velocity controls
AquidneckIslandRobotics/FRC78_2024 pull request #17
Opened 2024-01-16 00:11 UTC by tsieben

2024-01-16 02:52 UTC, ArchdukeTim requested changes

2024-01-16 02:52 UTC, ArchdukeTim commented on src/main/java/frc/robot/Commands/Shoot.java
> +    shooter = subsystem1;
```suggestion
  public Shoot(Shooter shooter) {
    // Use addRequirements() here to declare subsystem dependencies.
    this.shooter = shooter;
```

2024-01-16 02:52 UTC, ArchdukeTim commented on src/main/java/frc/robot/RobotContainer.java
> +  //private Chassis m_chassis;
Why comment out the drive code? I know it's not used for the shooter test, but shouldn't interfere with it

2024-01-16 02:52 UTC, ArchdukeTim commented on src/main/java/frc/robot/Systems/Shooter.java
> +    //shooterBOTTOM.restoreFactoryDefaults();
I think I lied. This probably _is_ ok to do. I think what we don't want to do is call the `burnFlash` method, but even that isn't fully agreed upon on chief Delphi 🤷🏼

2024-01-19 12:50 UTC, siebs7317 commented
Closing this pull request since the decision was made to switch to Falcon/CTRE motors rather than REV/Neo.

2024-01-19 12:50 UTC, closed without merging