WIP: April tags
AquidneckIslandRobotics/FRC78_2024 pull request #18
Opened 2024-01-16 00:14 UTC by tsieben

2024-01-16 03:25 UTC, ArchdukeTim requested changes

2024-01-16 03:25 UTC, ArchdukeTim commented on src/main/java/frc/robot/Systems/Chassis/Chassis.java
> +import javax.swing.text.html.Option;
```suggestion
```

2024-01-16 03:25 UTC, ArchdukeTim commented on src/main/java/frc/robot/Systems/Chassis/Chassis.java
> +  public SwerveModulePosition[] getPositions;
These are kinda confusing names. Maybe something like `requested` and `actual`

2024-01-16 03:25 UTC, ArchdukeTim commented on src/main/java/frc/robot/Systems/Chassis/Chassis.java
> +    }
I wonder if it would be better to update the 'actual positions' array in `periodic`, and this is just a normal getter that returns that array.  🤔

2024-01-16 03:25 UTC, ArchdukeTim commented on src/main/java/frc/robot/Systems/Chassis/Chassis.java
>      drive();
I would combine these methods and don't save `setChassisSpeed` anywhere.

2024-01-16 03:25 UTC, ArchdukeTim commented on src/main/java/frc/robot/Systems/Chassis/Chassis.java
> +      SmartDashboard.putNumber(i +" Rot", setStates[i].angle.getRadians());
Should this be here or in the module `periodic`?

2024-02-04 02:34 UTC, tsieben commented
Is this request still needed? Does this provide functionality the April Tags targeting branch didn't add?

2024-02-04 07:03 UTC, closed without merging