DCMP
AquidneckIslandRobotics/FRC78_2024 pull request #191
Opened 2024-04-09 21:19 UTC by MaddieG56

Code and updates from DCMP

2024-04-09 21:52 UTC, ArchdukeTim requested changes

2024-04-09 21:52 UTC, ArchdukeTim commented on src/main/deploy/pathplanner/paths/idkWhyButItNeedsToBeThis.path
Let's put this back to W1.W2.path

We can load onto the robot to see if it crashes but I could not reproduce in simulator

2024-04-09 21:52 UTC, ArchdukeTim commented on src/main/java/frc/robot/commands/VarFeedPrime.java
> +    lInput.setDefaultDouble(3);
Let's get rid of these if they're unused

2024-04-09 22:08 UTC, MaddieG56 commented on src/main/deploy/pathplanner/paths/idkWhyButItNeedsToBeThis.path
Changed in the World Auto Dev Branch

2024-04-10 01:03 UTC, ArchdukeTim approved these changes

2024-04-10 01:03 UTC, merged