Falcon cartridge
AquidneckIslandRobotics/FRC78_2024 pull request #27
Opened 2024-01-19 12:52 UTC by siebs7317

* This is the implementation of two falcon motors to control the cartridge/shooter mechanism.
* Utilizes the built-in PID voltage velocity controls from the v6 ctre library.
* Instructions for getting the proper gains is located in the team drive folder

2024-02-03 18:31 UTC, tsieben requested changes

2024-02-03 18:31 UTC, tsieben commented on src/main/java/frc/robot/Commands/Shoot.java
This command should be turned into the Command factory within the subsystem.

2024-02-03 18:31 UTC, tsieben commented on src/main/java/frc/robot/Constants/RobotConstants.java
These constants will need to be added to be calculated and added to the Competition Robot constants.

2024-02-03 18:31 UTC, tsieben commented on src/main/java/frc/robot/RobotContainer.java
This will need to be added to the competition RobotContainer along with pointing to new command factories.

2024-02-03 22:36 UTC, tsieben submitted a review, later dismissed

2024-02-03 22:36 UTC, tsieben commented on src/main/java/frc/robot/subsystems/Shooter.java
> +        shooterTopVV.withVelocity(setPoint * 60).withFeedForward(config.FLYWHEEL_TOP_FF));
This needs to be changed to a divide by 60 to convert RPM to RPS

2024-02-03 22:36 UTC, tsieben commented on src/main/java/frc/robot/subsystems/Shooter.java
> +        shooterBottomVV.withVelocity(setPoint * 60).withFeedForward(config.FLYWHEEL_BOTTOM_FF));
Same with this math

2024-02-04 06:14 UTC, ArchdukeTim approved these changes

2024-02-04 06:16 UTC, merged