Intake controls
AquidneckIslandRobotics/FRC78_2024 pull request #38
Opened 2024-01-27 17:27 UTC by tbriden

2024-01-27 17:30 UTC, tsieben commented on src/main/java/frc/robot/competition/CompetitionRobotContainer.java
> +    configureIntake();
I don't necessarily think we need to create a separate method to just instantiate the intake subsystem.

2024-01-27 17:31 UTC, tsieben commented on src/main/java/frc/robot/subsystems/Intake.java
May want to add the factory classes here instead of creating the separate commands.

2024-01-27 17:33 UTC, tsieben approved these changes
Left few comments on the improvements that Tim W mentioned but approved.

2024-01-28 04:38 UTC, ArchdukeTim requested changes

2024-01-28 04:38 UTC, ArchdukeTim commented on src/main/java/frc/robot/commands/IntakeNote.java
Convert this class to two command factory methods in the `Intake` subsystem

2024-02-02 03:03 UTC, ArchdukeTim approved these changes

2024-02-02 03:39 UTC, merged